version: '3.7'

services:
  minio:
    image: minio/minio
    command: ["server", "/data"]
    volumes:
      - "./volumes/data:/data:delegated"
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    ports:
      - "9000:9000"

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - "./volumes/data/:/var/www/:ro"
    depends_on:
      - minio
      - pulitzer
    ports:
      - "8080:80"

  pulitzer:
    image: nonsensebb/pulitzer:latest
    environment:
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: image-host.example.com
      S3_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      S3_SECRET_KEY: ${MINIO_SECRET_KEY}
    depends_on:
      - minio
